name: RPPersonas
version: ${project.version}
main: net.korvic.rppersonas.RPPersonas
api-version: '1.16'
depend: [Tythan, ProtocolLib]
softdepend: [Votifier, Dynmap, PlaceholderAPI, Multiverse-Core, DependencyLoader]
commands:
  account:
    command: /<command>
    description: "Account link, menus, and other management options."
  persona:
    command: /<command>
    description: "Check, set, and update persona info."
  rpp:
    command: /<command>
    description: "Misc Staff Commands."
  time:
    command: /<command>
    description: "Retrieve or adjust the time."
  date:
    command: /<command>
    description: "Get the current ages since arriving on Anoma."
permissions:
  rppersonas.accepted:
    default: op
    description: "Differentiate users who've been accepted via greylist application."
  rppersonas.link:
    default: true
    description: "Allow the user to link their Forum and Discord IDs."
  rppersonas.corpsebypass:
    default: op
    description: "Allow the user to add items to a corpse's inventory. Still cannot nest."