name: RPPersonas
version: ${project.version}
main: net.korvic.rppersonas.RPPersonas
api-version: 1.13
depend: [Tythan]
commands:
  account:
    command: /<command>
    description: "Link your Minecraft and forum accounts."